"""add session user_oauth_token tables and extend account

Revision ID: 38b5a2a98694
Revises: 0154725d6a01
Create Date: 2026-08-07 15:48:43.136588

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38b5a2a98694'
down_revision: str | None = '0154725d6a01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_oauth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_oauth_tokens_user_id'), 'user_oauth_tokens', ['user_id'], unique=True)
    op.add_column('accounts', sa.Column('github_account_id', sa.BigInteger(), nullable=True))
    op.add_column('accounts', sa.Column('account_type', sa.String(length=32), nullable=False))
    op.add_column('accounts', sa.Column('suspended_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_accounts_github_account_id'), 'accounts', ['github_account_id'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'encrypted_oauth_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_oauth_token', sa.TEXT(), nullable=True))
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'avatar_url')
    op.drop_index(op.f('ix_accounts_github_account_id'), table_name='accounts')
    op.drop_column('accounts', 'suspended_at')
    op.drop_column('accounts', 'account_type')
    op.drop_column('accounts', 'github_account_id')
    op.drop_index(op.f('ix_user_oauth_tokens_user_id'), table_name='user_oauth_tokens')
    op.drop_table('user_oauth_tokens')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
